### ISSUE TITLE
leiningen.core.user/gpg map returned is inconsistent

### ISSUE THREAD

**Issue by miikka** [technomancy/leiningen#2236]
```
% lein deps :verify
gpg: assuming signed data in '/Users/miikka/.m2/repository/instaparse/instaparse/1.4.0/instaparse-1.4.0.jar'
gpg: Signature made Ke  6 Tou 11:48:18 2015 EEST
gpg:                using RSA key 0x1B5C6189B92AC759
gpg: Can't check signature: No public key
java.lang.NullPointerException: null
 at java.util.regex.Matcher.getTextLength (Matcher.java:1283)
    java.util.regex.Matcher.reset (Matcher.java:309)
    java.util.regex.Matcher.<init> (Matcher.java:229)
    java.util.regex.Pattern.matcher (Pattern.java:1093)
    clojure.core$re_matcher.invokeStatic (core.clj:4674)
    clojure.core$re_find.invokeStatic (core.clj:4716)
    clojure.core$re_find.invoke (core.clj:4716)
    leiningen.deps$fetch_key.invokeStatic (deps.clj:28)
    leiningen.deps$fetch_key.invoke (deps.clj:27)
    leiningen.deps$check_signature.invokeStatic (deps.clj:41)
    leiningen.deps$check_signature.invoke (deps.clj:37)
 (rest of the stacktrace omitted)
```

In this example it happens because the public key is not found, but [looking at the code](https://github.com/technomancy/leiningen/blob/a76de08f0da4c5ca95ceaf1421f0122b2df044a1/src/leiningen/deps.clj#L37-L41), it happens if `gpg` returns a non-zero exit code for any reason while checking a signature. The trouble is that [`user/gpg` does not return stderr in `:err`](https://github.com/technomancy/leiningen/blob/master/leiningen-core/src/leiningen/core/user.clj#L106-L122) anymore. This means that even if `fetch-key` could handle a nil, it wouldn't fetch any GPG keys because the error message detection wouldn't work.

**Comment by LoganGirard** [comment]
I've been looking into this. I'm able to repro this on stable but not on master. Can anyone else corroborate that? Seems like this was somehow fixed in a checkin, but I haven't been able to identify what check in that is or why.

**Comment by miikka** [comment]
Hey, thanks for looking into this! I just tried out this on master and I still get the error. If you're reproducing this in the Leiningen repo, I wonder if it's possible that the dependencies have changed and you have all the public keys for them, so that this error does not happen anymore.

I'm new to Leiningen development, but here's what I did:
1. cloned this repo and ran `lein bootstrap` under `leiningen-core`
2. ran `bin/lein deps :verify` on the top level. I don't have the public key for bultitude, so this is what I got again:
```
% bin/lein deps :verify
Recalculating Leiningen's classpath.
Tried to load org.apache.httpcomponents/httpcore version 4.2 but 4.4.4 was already loaded.
Tried to load org.apache.httpcomponents/httpclient version 4.2 but 4.5.3 was already loaded.
Tried to load commons-codec version 1.6 but 1.9 was already loaded.
Tried to load commons-logging version 1.1.1 but 1.2 was already loaded.
gpg: assuming signed data in '/Users/miikka/.m2/repository/bultitude/bultitude/0.2.8/bultitude-0.2.8.jar'
gpg: Signature made Pe 17 Hei 20:53:24 2015 EEST using RSA key ID 57CADCAE
gpg: Can't check signature: No public key
java.lang.NullPointerException: null
(rest of the stacktrace omitted)
```

**Comment by danielcompton** [comment]
@miikka which version of GPG are you using?

**Comment by miikka** [comment]
```
gpg (GnuPG/MacGPG2) 2.0.30
libgcrypt 1.6.6
```

**Comment by miikka** [comment]
Hey, by the way! Leiningen does not always download the signature files for JARs. For example, if I run `rm -r ~/.m2/repository/bultitude` and re-run `lein bootstrap`, the .asc file won't be downloaded even though [it exists on Clojars](https://repo.clojars.org/bultitude/bultitude/0.2.8/).

I don't know if this is a bug or expected behavior. I've encountered this a couple times before, but I've never investigated it.

**Comment by glts** [comment]
I would also like to get this fixed, but I think we need some outline of what is a desirable solution (= not sure about the newbie label).

Currently `user/gpg` pipes the process's stderr to `System/err`, but slurps stdout into a string to be returned in the result map. I think stderr needs to be slurped too and returned under the `:err` key, but should also still get copied to `System/err`. This will need a `tee` like construct in place of @hyPiRion's `com.hypirion.io.Pipe`. If maintainers agree with this approach we could either use commons-io's `TeeOutputStream` or roll our own.

In any case I can reproduce the issue with GnuPG 1.4.20 and 2.1.11.

**Comment by glts** [comment]
Just to follow up with some code …

```diff
--- a/leiningen-core/src/leiningen/core/user.clj
+++ b/leiningen-core/src/leiningen/core/user.clj
@@ -113,11 +114,15 @@
       (.addShutdownHook (Runtime/getRuntime)
                         (Thread. (fn [] (.destroy proc))))
       (with-open [out (.getInputStream proc)
-                  err (.getErrorStream proc)]
-        (let [pump-err (doto (Pipe. err System/err) .start)]
+                  err-output (ByteArrayOutputStream.)]
+        (let [pump-err (doto (Pipe. (.getErrorStream proc)
+                                    (TeeOutputStream. System/err err-output))
+                         .start)]
           (.join pump-err)
           (let [exit-code (.waitFor proc)]
-            {:exit exit-code :out (slurp (InputStreamReader. out))}))))
+            {:exit exit-code
+             :out (slurp (io/reader out))
+             :err (slurp (io/reader (.toByteArray err-output)))}))))
     (catch java.io.IOException e
       {:exit 1 :err (.getMessage e)})))
```

This works for me, maybe you prefer a different approach. I didn’t look into unit testing.

**Comment by technomancy** [comment]
Sorry for the confusion here. The issue indeed is that the keys which are present in the map which is returned are inconsistent. This looks like a good fix, but it would be even better if the map in the `catch` clause also included an `:out` key, even if it's an empty string.

I could see this being very difficult to write a unit test for, so if there's no easy way to proceed on that front then I'd be OK with just manual testing.
